import { NumberMeaning, EnergyType } from './types';

export const AURORA_MEANINGS: Record<number, NumberMeaning> = {
  1: {
    keywords: ["Liderlik", "Başlangıç", "Ego", "Cesaret"],
    element: EnergyType.FIRE,
    chakra: "Solar Pleksus",
    archetype: "Savaşçı / Lider",
    light: ["Öncü", "Bağımsız", "Hızlı Karar", "Koruyucu"],
    shadow: ["Kibir", "Öfke", "Baskıcı", "Bencil"],
  },
  2: {
    keywords: ["Duygu", "Uyum", "İlişki", "Empati"],
    element: EnergyType.WATER,
    chakra: "Sakral",
    archetype: "Aşık / Destekleyici",
    light: ["Nazik", "Diplomatik", "Sadık", "Sezgisel"],
    shadow: ["Bağımlı", "Kırılgan", "Aşırı Hassas", "Kararsız"],
  },
  3: {
    keywords: ["Düzen", "İfade", "Disiplin", "Strateji"],
    element: EnergyType.FIRE,
    chakra: "Solar Pleksus",
    archetype: "Komutan / Sistem Kurucu",
    light: ["Organize", "Net", "Sosyal", "Yaratıcı"],
    shadow: ["Dağınık", "Eleştirel", "Sert", "Yüzeysel"],
  },
  4: {
    keywords: ["Sabır", "Köklenme", "Güven", "İnşa"],
    element: EnergyType.EARTH,
    chakra: "Kök",
    archetype: "İnşa Eden / Gerçekçi",
    light: ["Güvenilir", "Çalışkan", "Pratik", "Sadık"],
    shadow: ["İnatçı", "Katı", "Vizyonsuz", "Aşırı Garantici"],
  },
  5: {
    keywords: ["Değişim", "Özgürlük", "İletişim", "Zeka"],
    element: EnergyType.AIR,
    chakra: "Boğaz",
    archetype: "Gezgin / İletişimci",
    light: ["Hızlı", "Esnek", "Maceracı", "İkna Edici"],
    shadow: ["Kaotik", "Dürtüsel", "Güvenilmez", "Bağımlı"],
  },
  6: {
    keywords: ["Aile", "Sorumluluk", "Sevgi", "Hizmet"],
    element: EnergyType.WATER,
    chakra: "Kalp",
    archetype: "Ebeveyn / Koruyucu",
    light: ["Şefkatli", "Sorumlu", "Estetik", "İyileştirici"],
    shadow: ["Kıskanç", "Müdahaleci", "Mükemmeliyetçi", "Şehit"],
  },
  7: {
    keywords: ["Bilgelik", "Analiz", "Ruhsallık", "Yalnızlık"],
    element: EnergyType.SOUL,
    chakra: "Üçüncü Göz",
    archetype: "Bilge / Araştırmacı",
    light: ["Derin", "Analitik", "Spiritüel", "Zeki"],
    shadow: ["Mesafeli", "Kuşkucu", "Melankolik", "Soğuk"],
  },
  8: {
    keywords: ["Güç", "Para", "Yönetim", "Otorite"],
    element: EnergyType.EARTH,
    chakra: "Taç / Kök",
    archetype: "Yönetici / Kral",
    light: ["Başarılı", "Güçlü", "Vizyoner", "Organizatör"],
    shadow: ["Materyalist", "Baskıcı", "Hırslı", "Acımasız"],
  },
  9: {
    keywords: ["Tamamlanma", "Şifa", "Evrensel Sevgi", "Sanat"],
    element: EnergyType.WATER,
    chakra: "Kalp / Taç",
    archetype: "Şifacı / Hümanist",
    light: ["Cömert", "Sanatsal", "Anlayışlı", "Fedakar"],
    shadow: ["Dramatik", "Dağınık", "Kurban", "Gerçeklerden Kopuk"],
  },
  11: {
    keywords: ["Aydınlanma", "İlham", "Sezgi", "Vizyon"],
    element: EnergyType.SOUL,
    chakra: "Taç (Üst)",
    archetype: "Işık İşçisi",
    light: ["İlham Veren", "Kanal", "Yüksek Sezgi"],
    shadow: ["Gergin", "Fanatik", "Hayalperest"],
  },
  22: {
    keywords: ["Usta İnşacı", "Büyük Plan", "Gerçekleştirme"],
    element: EnergyType.EARTH,
    chakra: "Taç (Üst)",
    archetype: "Usta Mimar",
    light: ["Vizyonu Maddeye Döken", "Global Etki"],
    shadow: ["Yıkıcı", "Aşırı Hırs", "Manipülatif"],
  },
  33: {
    keywords: ["Üstad Öğretmen", "Koşulsuz Sevgi", "Hizmet"],
    element: EnergyType.WATER,
    chakra: "Taç (Üst)",
    archetype: "İlahi Şifacı",
    light: ["Evrensel Şefkat", "Ruhsal Rehber"],
    shadow: ["Duygusal Çöküş", "Kendini Feda"],
  },
};
